# Generated by Django 4.2.27 on 2026-01-20 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_alter_comment_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="favourites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourite_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
