# Generated by Django 4.2.27 on 2026-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submit",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
