# Generated by Django 4.2.27 on 2026-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0002_submit_updated_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("submission", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
